### ISSUE TITLE
"Save as HTML" is missing from the Respec menu

### ISSUE THREAD

**Issue by tantek** [w3c/respec#1450] opened 2018-01-01 04:12 UTC
"Save as HTML" is missing from the ReSpec menu

E.g. see: http://ptd.spec.indieweb.org/index-src.html
or http://ptd.spec.indieweb.org/index-wd-src.html (both in Firefox)

This is blocking publication of an end of year NOTE because Echidna requires full server-side HTML, not just JS-generated on the client.

**Comment by marcoscaceres** [comment] 2018-01-01 06:44
Odd, will take a look. Echidna should still be able to publish, as the export API is independent of the save button. But still weird that the menu option vanished.

**Comment by tantek** [comment] 2018-01-01 21:04
Yes all gone. All I see is Save Snapshot which brings up ust EPUB3. Y THO.

Can't publish with Echidna because can't be sure it passes all of Echidna's tests (even if Echidna does somehow magically know to call an export API when given a specific HTML file?). E.g. Specberus also requires a static all-inclusive HTML file to check AFAIK.

**Comment by marcoscaceres** [comment] 2018-01-01 21:26
Trying to reproduce - but was unable to. Can you confirm the ReSpec version for me? Click the ReSpec pill, and hit "About ReSpec". It should say 19.0.1.

**Comment by tantek** [comment] 2018-01-01 23:49
Confirmed: About ReSpec - 19.0.1. Screenshot of menu when viewing http://ptd.spec.indieweb.org/index-src.html:

![screen shot 2018-01-01 at 15 47 35](https://user-images.githubusercontent.com/46418/34471974-2f6d061a-ef0b-11e7-886d-8709888bdfa1.png)

No "Save as HTML" as expected (and was there at least as recently as last August).

**Comment by marcoscaceres** [comment] 2018-01-02 03:42
The “Save Snapshot” should have the “Save as HTML” option - so it’s really strange that it’s just showing EPUB. I’ll try a few different versions of Firefox. In the meantime, hopefully it’s fine in Chrome in case you need to export. I’m currently on vacation on the 🏖, but will try to find time to see what’s wrong in the next few days.

**Comment by marcoscaceres** [comment] 2018-01-02 10:50
@tantek I just realized that this is a duplicate of https://github.com/w3c/respec/issues/1440

Do you have [Adblock Ultimate](https://adblockultimate.net/) installed?

**Comment by marcoscaceres** [comment] 2018-01-02 10:55
For record keeping purposes, without browser extensions, 57: 

![screen shot 2018-01-02 at 8 46 11 pm](https://user-images.githubusercontent.com/870154/34481633-fe53e428-effe-11e7-93f9-afbec24ee97e.png)

And 59: 
![screen shot 2018-01-02 at 8 44 43 pm](https://user-images.githubusercontent.com/870154/34481640-06656ede-efff-11e7-915f-5049d094370c.png)

So likely this is a browse extension removing these, possibly because they are either data URLs or have a `download` attribute.

**Comment by tantek** [comment] 2018-01-13 00:02
Confirmed that a fresh Nightly FF shows the Save as HTML option - used that for now. Now to try to narrow down what browser extension could be interfering.

**Comment by tantek** [comment] 2018-01-13 00:07
FWIW I have 
* Privacy Badger version 2017.11.20
* AdBlocker Ultimate 2.31  [note the -er on the end. Adblocker, not Adblock]
Following your suspicion about the latter, I chose "Options" from the AdBlocker Ultimate toolbar icon dropdown menu, then "Whitelisted domains" and add ptd.spec.indieweb.org. Reloading http://ptd.spec.indieweb.org/index-src.html then showed the Save as HTML button.

**Comment by marcoscaceres** [comment] 2018-01-13 05:10
I think the only thing we can do here is just let spec-prod@w3c know. Might also see if I can let tge extension owner know that it’s blocking us incorrectly.

**Comment by marcoscaceres** [comment] 2018-01-16 01:25
Ok, I've emailed spec-prod and filed a bug with AdBlocker Ultimate. Closing as there is not much more I can do from here.

**Closed by marcoscaceres** 2018-01-16 01:25 UTC
