### ISSUE TITLE
ReSpec biblio processing broken in Firefox?

### ISSUE THREAD

**Issue by domenic** [w3c/respec#1285] opened 2017-06-21 03:33 UTC
See https://github.com/WICG/web-share/issues/41 (including comment with a stack trace) and https://wicg.github.io/web-share/. Notice the lack of biblio and linking to other specs, and the progress indicator that spins for a very long while before giving up.

However, in that issue Matt reports it works in his Firefox, so the first thing to do is confirm this happens on someone else's computer...

**Comment by marcoscaceres** [comment] 2017-06-21 03:37
thanks, having a look!

**Comment by marcoscaceres** [comment] 2017-06-21 03:39
confirmed in Firefox 53. Checking 54. Works fine in nightly.

**Comment by marcoscaceres** [comment] 2017-06-21 08:45
I'm hitting a [gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1362878) that seems to be fixed in Nightly.

**Closed** 2017-06-21 09:51 UTC
Labels: bug
