### ISSUE TITLE
Respec2HTML randomly fails to show warnings when using webpack build

### ISSUE THREAD

**Issue by devanshbatra04** [w3c/respec#2227] opened 2019-04-03 17:49 UTC
On running Respec2HTML on documents using the ```builds/respec-w3c-common.js```, Respec2HTML randomly fails to list ToC warnings. (See screenshot)

I am unsure if this has anything to do with #2057. I also suspect #2010 might be the cause instead. FWIW, this does not happen on using RequireJS with ```profile-w3c-common```. I will look into this as its blocking #2205 
![Screenshot from 2019-04-03 23-09-10](https://user-images.githubusercontent.com/33961252/55500766-918b7700-5666-11e9-818f-4dafe31cf1cf.png)

**Comment by marcoscaceres** [comment] 2019-04-03 18:53
@devanshbatra04 can you try it with a local server? i.e., http://localhost:5000/tests/respec2html/ interested to see if it's related to that.

**Comment by devanshbatra04** [comment] 2019-04-03 19:14
Yes. Same thing. I actually encountered this on the server first, while working on #2205 
I am positive it's a fixup.js issue

**Comment by marcoscaceres** [comment] 2019-04-03 19:21
Maybe https://github.com/w3c/respec/issues/2010 ...

**Comment by devanshbatra04** [comment] 2019-04-03 19:22
Yes. Same thoughts. I wasn't sure though, so avoided commenting over there. 
Will give it a more in-depth look in an hour or two.

**Comment by saschanaz** [comment] 2019-04-04 01:16
This is indeed #2010. The fixup.js includes this line:

```js
console.warn("Can't find Table of Contents. Please use <nav id='toc'> around the ToC.");
```

**Comment by devanshbatra04** [comment] 2019-04-04 06:23
I guess I will use another set of warnings in the PR in this case so this is no longer a blocker.

**Comment by marcoscaceres** [comment] 2019-12-29 03:57
Closing as duplicate of #2010.

**Closed by marcoscaceres** 2019-12-29 03:57 UTC
