### ISSUE TITLE
Support for darkmode

### ISSUE THREAD

**Issue by OR13** [w3c/respec#4543] opened 2023-09-18 19:43 UTC
**Is your feature request related to a problem? Please describe.**

IETF recently added darkmode support to data tracker. 
I prefer darkmode when possible, and wonder if others would be interested in darkmode support for respec.

**Describe the solution you'd like**

Ideally, detect user preferences and render respec accordingly.

I've some experience with system preference side of this using material ui, perhaps the same approach could be applied to respec.

https://mui.com/material-ui/customization/dark-mode/

**Additional context**

There might be other benefits from supporting dark mode that align with design guidelines or w3c values.

https://dl.acm.org/doi/pdf/10.1145/3458864.3467682

**Describe any alternatives you've considered**

No dark mode support for respec.

**Can you or your organization fund the work or help with development?**

I can help contribute, but it would probably require more than just one contributor to land this feature.

I can't provide funding, but I will leave the boilerplate here in case others are interested in doing so:

1. contribute to the project yourself via a pull request. We will [guide](https://respec.org/docs/#developers-guide) you!
2. fund a contributor to prioritize your feature (usually US$500+ depending on complexity).
3. wait for someone to get to it (usually a few months).

Funding pays for the feature development, testing, documentation, server costs, etc. We have an open collective where development costs are tracked and shared. Please see our [Open Collective](https://opencollective.com/respec/).

**Comment by sidvishnoi** [comment] 2023-09-19 09:59
I worked on it a while ago in https://github.com/w3c/respec/pull/3236, almost finished it, but then lost track of it with all _things happening around_. That PR now has _some_ merge conflicts, and needs some rework on style loading. I'll try to find time for it after next two weeks.

For now, closing this one as duplicate of https://github.com/w3c/respec/issues/2651.

**Closed by sidvishnoi** 2023-09-19 09:59 UTC
Labels: Feature request
