### ISSUE TITLE
Question about IDL classes and properties

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#1530] opened 2018-02-23 16:23 UTC
A member of the ARIA group sent me the following question...   @marcoscaceres do you have an opinion?   

I am working on the ARIA attribute-reflection branch for Issue #691. I attempted to define the “Role” interface in IDL with a single “role” attribute. However, this is either an IDL error or it’s a ReSpec parsing bug that does not allow the interface name and attribute name to be the same. If you use the <dfn> elements as expected, there is a case-insensitive match, and ReSpec throws an error that you’re defining the interface or attribute twice.
```
interface mixin Role {
    attribute DOMString? role;
};
Element includes Role;
```
If I change the interface name, it works. As it is now, the “RoleInterface” interface is painfully redundant, but ReSpec parses the IDL as expected.

```
interface mixin RoleInterface {
    attribute DOMString? role;
};
Element includes RoleInterface;
```

**Comment by marcoscaceres** [comment] 2018-02-23 17:27
@halindrome, this is a current limitation because the linker code works case insensitively... so can't distinguish between `role` and `Role`. We have a bunch of open bugs for this.

However, specifically with you case, you should really call the mixing `interface mixin AccessibilityMixin {}`, so then if you need to, you can add more things than just `role`. 

That is:

```IDL
interface mixin AccessibilityMixin {
    attribute DOMString? role;
   // future stuff here
};
Element includes AccessibilityMixin;
```

**Comment by marcoscaceres** [comment] 2018-02-23 23:23
Closing, as this is a duplicate of known issue. Happy to discuss further tho!

**Closed by marcoscaceres** 2018-02-23 23:23 UTC
Labels: question
