### ISSUE TITLE
WebIDL name collision issue

### ISSUE THREAD

**Issue by danielpeintner** [w3c/respec#1508] opened 2018-02-14 12:50 UTC
We, the WoT Scripting API taskforce, run into a little issue with respec when having the same name (even though with different spelling) in WebIDL.

Please take a look at https://rawgit.com/w3c/wot-scripting-api/45666df86df76a7dc76a085c48d1e5d6183a5a42/index.html

In Section "5.7.1 The ThingPropertyInit dictionary" we have `boolean    observable = true;`.

In Section "6. Observables" we have `interface Observable ...`.

Having the same name causes respec error "`No <dfn> for interface Observable.`".

This problem disappears IF we rename the first snippet to `boolean    observableX = true;` for example.

I would think our use of WebIDL is correct? Hence I assume this is a bug or is there anything else we can do to work around it.

Thanks,

-- Daniel

**Comment by dontcallmedom** [comment] 2018-02-14 13:18
I hit the same issue recently - the workaround is to use `data-dfn-for=""` on the `<dfn>` used to markup the definition associated with the interface - see also https://github.com/w3c/webrtc-pc/commit/9403a1b3dc67db3243ba15f55e98fd6cac928175

**Comment by dontcallmedom** [comment] 2018-02-14 13:18
(leaving the issue open since avoiding the need for that workaround would be nice)

**Comment by marcoscaceres** [comment] 2018-02-15 04:14
@danielpeintner please also have a quick look at https://github.com/w3c/respec/wiki/WebIDL-Guide

We are working on trying to make ReSpec smarter as part of #1050.

**Comment by saschanaz** [comment] 2018-02-15 05:18
```html
<section data-dfn-for="Observable">
  <h3>The <dfn>Observable</dfn> interface</h3>
  ...
</section>
```

This is a weird situation, the parent `data-dfn-for` makes `<dfn>Observable</dfn>` be resolved like `observable.Observable`. Currently ReSpec first searches the top level `dfn`, then tries lower levels as a workaround.

https://github.com/w3c/respec/blob/29aebe1ebda0a83577eb1c829e0f69d148a4f399/src/core/webidl.js#L972-L976

But it didn't work because of the `boolean observable`.

**Comment by saschanaz** [comment] 2018-02-15 05:25
Currently the definition map is case insensitive, will there any problems if it becomes case sensitive? @marcoscaceres

**Comment by marcoscaceres** [comment] 2018-02-15 05:27
Not for IDL links, but yes for others... so we need to distinguish them.

**Comment by marcoscaceres** [comment] 2019-04-23 15:34
Closing as duplicate of #1050.

**Closed by marcoscaceres** 2019-04-23 15:34 UTC
