### ISSUE TITLE
Logos for custom profile layout issue

### ISSUE THREAD

**Issue by Evadon-Nathan** [w3c/respec#1181] opened 2017-04-12 17:18 UTC
I'm attempting to use the logos respecConfig option as part of creating a custom profile.

It appears that the logo inserted is not in the correct <p> tag in the source.

The css is looking for `.head p:first-child:not(.copyright)`, but the actual logo is inserted into a second <p> tag in the DOM and is therefore not aligned correctly.

Here's the relevant part of my respectConfig:
```JS
logos: [{
          src: "http://www.openmobilealliance.org/wp/Images/oma_logo.jpg",
          url: "http://openmobilealliance.org",
          alt: "Open Mobile Alliance"
        }]
```
If it helps, I have made a fix by removing the initial <p> tag in the showLogos helper in /src/headers.js (I'm not checking this in as I'm not too familiar with the code yet so there might be a better way to fix this, or it might break other things):

```JS
hb.registerHelper("showLogos", function(items) {
  //var ret = "<p>"; <---- Here
  for (var i = 0, n = items.length; i < n; i++) {
    var p = items[i];
    if (p.url) ret += "<a href='" + p.url + "'>";
    if (p.id) ret += "<span id='" + p.id + "'>";
    if (p.src) {
      ret += "<img src='" + p.src + "'";
      if (p.width) ret += " width='" + p.width + "'";
      if (p.height) ret += " height='" + p.height + "'";
      if (p.alt) ret += " alt='" + p.alt + "'";
      else if (items.length == 1) ret += " alt='Logo'";
      else ret += " alt='Logo " + (i + 1) + "'";
      ret += ">";
    } else if (p.alt) ret += p.alt;
    if (p.url) ret += "</a>";
    if (p.id) ret += "</span>";
  }
  //ret += "</p>"; <---- And here
  return new hb.SafeString(ret);
});
```

Thanks,
Nathan

**Comment by ridhishjain** [comment] 2019-12-09 17:34
@marcoscaceres, as no in assigned, can I work on this issue?

**Comment by sidvishnoi** [comment] 2019-12-09 19:02
@ridhishjain Sure. Go for it! 
This is an old issue though, so the code above is outdated - and the issue _might_ be already fixed.

**Comment by sidvishnoi** [comment] 2019-12-09 19:03
The code now lives in [src/w3c/templates/](https://github.com/w3c/respec/tree/91232584dd2163aa6a9222709e79fe8152a17b3a/src/w3c/templates/)

**Comment by ridhishjain** [comment] 2019-12-10 12:21
@sidvishnoi, I think, the issue is already resolved. The alignment of the logo is all good, and it is inserted in DOM's first child, not second
![Screenshot (51)](https://user-images.githubusercontent.com/45514905/70529029-98637580-1b75-11ea-9d50-133971b962f4.png)

**Comment by sidvishnoi** [comment] 2019-12-10 12:27
Looks right. Closing this as fixed.
@Evadon-Nathan please reopen if you believe something is wrong.

**Closed by sidvishnoi** 2019-12-10 12:27 UTC
Labels: bug, good first issue
