### ISSUE TITLE
Parsing xml in markdown gives lower case tags

### ISSUE THREAD

**Issue by pvgenuchten** [w3c/respec#1573] opened 2018-03-15 10:31 UTC
## Important info

* ReSpec version: 19.0.1

## Description of problem

I try to add xml snippets as part of markdown include using \`\`\`
(to indicate the encoding, using \`\`\`xml is not supported)
I noticed that tags are transformed to lowercase, which leads to invalid xml according to xsd

## Expected

XML tags keep original casing

## Reproduce

Try for example this snippet
```xml
<gmd:MD_RestrictionCode 
        codeList="http://www.isotc211.org/2005/resources/codeList.xml#MD_RestrictionCode"
        codeListValue="otherRestrictions"/>
```

**Comment by marcoscaceres** [comment] 2018-03-19 03:57
Confirmed. This might be a limitation of marked.js, which is the library we use for markdown parsing... however, would need to check what's going on.

**Comment by marcoscaceres** [comment] 2018-03-19 03:58
@pvgenuchten, ReSpec 20+ uses a newer version of marked.js. Could you confirm that it's still busted there?

**Comment by marcoscaceres** [comment] 2018-03-19 04:15
@pvgenuchten, ok, you just need to change the "<" to "&lt;":

```
      ```xml
      &lt;gmd:MD_RestrictionCode
              codeList="http://www.isotc211.org/2005/resources/codeList.xml#MD_RestrictionCode"
              codeListValue="otherRestrictions"/>
      ```
```

And it renders correctly: 

![screenshot 2018-03-19 15 13 31](https://user-images.githubusercontent.com/870154/37577744-1db6396e-2b88-11e8-9f59-edbde8a41c60.png)

I'm not sure we will be able to fix the larger problem, because it's actually the browser's HTML parser that is auto-closing the tags in the example. But the above works ok.

**Comment by marcoscaceres** [comment] 2018-03-19 04:16
Closing as won't fix, as the work around is ok.

**Closed by marcoscaceres** 2018-03-19 04:16 UTC
Labels: bug
