### ISSUE TITLE
dfn-panel information not available for keyboard and screen reader users

### ISSUE THREAD

**Issue by jnurthen** [w3c/respec#3431] opened 2021-03-31 22:38 UTC
## Important info

- URL to affected spec: https://w3c.github.io/aria
- ReSpec version: 26.5.0
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

The popup (dfn-panel) is not available for keyboard or screen reader users. It only appears on a pointer click on a `<dfn>` or other element where the defintion is defined. This functionality is not available for either keyboard or screen reader users

**What happened (e.g., it crashed)?:**

Can't get to this information

**Expected behavior (e.g., it shouldn't crash):**

Info should be available for everyone

**Optional, steps to reproduce:**

1.  go to https://w3c.github.io/aria/#dfn-accessibility-api
2. click on "Accessibility API"
3. Note the popup
4. Try to do the same using only the keyboard

**Comment by jnurthen** [comment] 2021-03-31 22:53
seems to be duplicate of #2825 - but please note that this is a blocker for moving the ARIA spec to using this for all our definitions.

**Comment by marcoscaceres** [comment] 2021-04-08 09:14
closing as duplicate of #2825 ... picking up discussion there.

**Closed by marcoscaceres** 2021-04-08 09:14 UTC
Labels: bug
