### ISSUE TITLE
Wrong header level

### ISSUE THREAD

**Issue by lanthaler** [w3c/respec#386] opened 2014-12-23 19:32 UTC
A recent update apparently started to change the header level for JavaScript-injected content in our spec.

If you look at http://www.hydra-cg.com/spec/latest/core/#classes you'll see that not only *6. Classes* is a `h2` but also *hydra:ApiDocumentation* and *hydra:Class*. The HTML we inject sets uses `h3` but ReSpec changes them to `h2`. Please note that [the TOC is correct](http://www.hydra-cg.com/spec/latest/core/#h-toc).

The script that injects this content can be found here: https://github.com/HydraCG/Specifications/blob/master/spec/js/respec-w3c-extensions.js#L53-L64

This was originally reported as HydraCG/Specifications#78

**Comment by darobin** [comment] 2015-01-23 10:01
Hmmm, this looks like a problem with the order in which modules are run.

**Comment by darobin** [comment] 2015-01-25 08:16
Okay, I've looked at your code and I'm in fact seeing erratic behaviour that I *suspect* is not ReSpec's fault. You appear to be generating your content in the callback from `getJSON()`. The problem is that `getJSON()` is asynchronous, so the content is getting inserted at potentially unpredictable moments.

This doesn't mean that there isn't also a problem in ReSpec, but you should probably try loading content synchronously first. We can't make guarantees as to when the loop is spun or generally defend against race conditions like that.

**Comment by marcoscaceres** [comment] 2016-03-11 01:45
Marking as invalid based on Robin's analysis

**Closed by marcoscaceres** 2016-03-11 01:45 UTC
