### ISSUE TITLE
Snapshot menu not working on Firefox 57?

### ISSUE THREAD

**Issue by iherman** [w3c/respec#1440] opened 2017-12-06 13:01 UTC
When trying to make a snapshot of a file on Firefox 57, the pop-up menu contains a reference to EPUB3 only. See for example, https://w3c.github.io/publ-loc/?specStatus=FPWD, with the screendump below.

![screenshot-2017-12-6 locators for web publications](https://user-images.githubusercontent.com/520723/33662868-d259189c-da8d-11e7-8cf2-80abaef1c7be.png)

It seems to work all right on a chromium based browser (I tried Opera): I get, besides EPUB3, a possibility to dump into HTML and XML.

**Comment by iherman** [comment] 2017-12-06 13:02
(I use https://www.w3.org/Tools/respec/respec-w3c-common to link to respec.)

**Comment by iherman** [comment] 2017-12-06 13:10
Sorry, as a further info (if it is important): I run FF 57.0.1 on a Mac Book Pro, OS X 10.11.6 (El Capitan).

**Comment by marcoscaceres** [comment] 2017-12-06 13:21
Thanks! All that info is super helpful. I’ll investigate what’s going on.

**Comment by marcoscaceres** [comment] 2017-12-19 03:37
@iherman, sorry, I was away last week traveling and just got back to this. I just tried to reproduce in Firefox, but was not able to. The doc you linked to is also now 404? 

Could you kindly try it again or send me a link to the new location of that document?  Thanks!

**Comment by iherman** [comment] 2017-12-19 11:04
Oops, I am sorry, @marcoscaceres! We have changed the title and the short name of the document, and I have therefore changed the name of the repository, too. Github redirects a bunch of things but not the github.io addresses. I did not realize I used this example, sorry about that...

Anyway. The new address is:

https://w3c.github.io/wpub-ann/?specStatus=FPWD

and the problem is the same at least on my machine.

**Comment by marcoscaceres** [comment] 2017-12-20 03:55
Hmm... so strange... was not able to reproduce in Firefox 57 with the same OS setup as you: I was able to see the buttons and managed to save the snapshot correctly. 

Might be you have an old version of ReSpec cached? The latest version is 19.0.1 (check via the ReSpec Pill, and hit "About ReSpec"). Let me know!

**Comment by iherman** [comment] 2017-12-20 06:17
@marcoscaceres it is definitely the last, (19.0.1) version (it links to the version on the W3C site, b.t.w.).

However: I did get one step closer. I started up FF in Save Mode (add-ons disabled) and then things work... Which means there is interference with one of the add-ons. Unfortunately I have a fair number of them, so it will take some time to track down which one is the problem (I do not know any better method then to selectively switch add-ons off, restart, and test). I am happy to do that (unless you have a quicker trick) but I am not sure when. Possibly later today, but you will be fast asleep by then...

**Comment by marcoscaceres** [comment] 2017-12-20 06:23
Unfortunately, probably won't be much I can do if it's a browser extension. I don't use any (apart from ad-block) so not sure how to work with them.

**Comment by iherman** [comment] 2017-12-20 06:25
> 
> Unfortunately, probably won't be much I can do if it's a browser extension. I don't use any (apart from ad-block) so not sure how to work with them.
> 

I guess it is still useful if I chase this down. It may give some insight (and document which one to avoid…)

**Comment by marcoscaceres** [comment] 2017-12-20 07:24
That would be great!

**Comment by marcoscaceres** [comment] 2017-12-20 09:29
It will hopefully fix itself once I drop jQuery’s popup in favor of using HTML’s dialog element. I’m hoping to do that switch next year.

**Comment by marcoscaceres** [comment] 2017-12-20 09:33
In any case, I imagine that you can whitelist github.io in the addon? That should hopefully fix things. Thanks again for figuring it out! If it comes up again, we can point people here. Closing for now.

**Closed by marcoscaceres** 2017-12-20 09:33 UTC
Labels: bug
