### ISSUE TITLE
Use monospace font for <a>s that link back to IDL

### ISSUE THREAD

**Issue by anssiko** [w3c/respec#1088] opened 2017-02-16 13:38 UTC
It'd be convenient if the `<a>`s in prose that link to IDL definitions would inherit the monospace font of the IDL block.

Given:
```
<section>
  <h2><dfn>Request</dfn> interface</h2>
  <pre class="idl">
    interface Request {};
  </pre>
  <p>An instance of <a>Request</a> allows you to make a request.</p>
</section>
````

(From: https://github.com/w3c/respec/wiki/WebIDL-Guide#defining-the-interface)

Expected rendering:

An instance of `Request` allows you to make a request.

Actual rendering:

An instance of Request allows you to make a request.

To get the expected result, one currently needs to e.g. wrap the `<a>`s in `<code>`, which seems redundant:

```
  <p>An instance of <code><a>Request</a></code> allows you to make a request.</a>
```

The established style is to use monospace font when referring to IDL definitions.

**Comment by marcoscaceres** [comment] 2017-02-16 14:42
@anssiko, to get the behaviour you want, you need to change the section element to:

```
<section data-link-for="Request">
```

Duplicate of https://github.com/w3c/respec/issues/1050

**Comment by anssiko** [comment] 2017-02-16 15:13
That appears not to work. What am I doing wrong?

Here's a minimal test case:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Title</title>
    <script 
     src='https://www.w3.org/Tools/respec/respec-w3c-common' 
     class='remove'></script>
    <script class='remove'>
      var respecConfig = {
        specStatus: "ED",
        editors: [{
          name: "Your Name",
          url: "http://your-site.com",
        }],
        processVersion: 2015,
        edDraftURI: "http://some.github.repo",
        shortName: "dahut"
      };
    </script>
  </head>
  <body>
    <section data-link-for="Request">
      <h2><dfn>Request</dfn> interface</h2>
      <pre class="idl">
        interface Request {};
      </pre>
      <p>An instance of <a>Request</a> allows you to make a request.</p>
    </section>
  </body>
</html>
```

**Comment by marcoscaceres** [comment] 2017-02-17 06:20
d'oh. Something is not right... that should totally work.

**Closed** 2017-02-17 08:13 UTC

**Comment by anssiko** [comment] 2017-02-17 09:02
Thanks! I'll owe you a 🍺

**Comment by marcoscaceres** [comment] 2017-02-17 10:04
Nah, the other way around. Need to investigate further - seems a set of commits have gone missing that caused this to regress.
