### ISSUE TITLE
Custom logos: width and height swapped in Firefox 56.0.1

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1391] opened 2017-10-17 07:00 UTC
In Firefox 56.0.1, when custom logos get used, the width and height of the logos get swapped, making the logos appear skewed, for instance:

https://w3c.github.io/sdw/ssn/

This currently renders in Firefox 56.0.1 as:
![Screenshot of the SSN Ontology spec headers taken in Firefox 56.0.1 with skewed OGC logo](https://user-images.githubusercontent.com/1122927/31650805-58769446-b319-11e7-897b-c108de5e671a.png)

Logos appeared correctly in previous versions of Firefox, and in all other browsers, so it may well be a bug in Firefox...

**Comment by marcoscaceres** [comment] 2017-10-17 09:44
Thanks! The whole custom logos code seems to be broken. I’m currently rewriting the idl code, so will take me maybe another week or two to get to this.

**Comment by marcoscaceres** [comment] 2017-10-18 05:05
So, confirmed the Firefox bug. It's fixed in 57 it seems - so probably won't fix as it will be adding code that we will have to just rip out again in like 2 weeks.

**Closed** 2017-10-18 05:05 UTC
