### ISSUE TITLE
Making copyright configurable for non-W3C specs

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#2243] opened 2019-04-09 23:32 UTC
## Important info

* URL to affected spec: N/A
* ReSpec version: 24.10.2
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

_Apologies in advance if there's already a solution for this problem_.

If used for non-W3C specs, the only way I know to modify the copyright holder(s) is to use `overrideCopyright`.

This, however, has two main issues:
1. The content of the `overrideCopyright` replaces both copyright notice and licence
2. The copyright notice is static, so the start / end year for the copyright needs to be hard-coded

A possible option could be to add a config param `copyright`, with the following properties:
- `url` (optional): the URL pointing to a copyright page
- `copyrightHolder` (mandatory): an array of objects with the following properties:
  - `name` (mandatory): the name of the copyright holder
  - `url` (optional): the URL pointing to the Web site of the copyright holder

**Comment by marcoscaceres** [comment] 2019-04-09 23:42
Duplicate of https://github.com/w3c/respec/issues/263 

Unfortunately, there is no good way around this at the moment. @andrea-perego, that's a good suggestion. However, I'd like move away from relying on the config and instead use HTML for this... but we will need to think of some sane way of marking it up.

**Comment by andrea-perego** [comment] 2019-04-09 23:53
Thanks, @marcoscaceres . 

The HTML option (I guess using still `overrideCopyright`) would indeed be fine, but there should be a way to fix issue (2) above - i.e., not being obliged to hard-code the copyright start/end year.

**Comment by marcoscaceres** [comment] 2019-04-09 23:56
Yeah, I was thinking something like some magic strings to replace:

```
<p class="copyright" data-start="iso-date" data-end="optional iso-date">
  ${start} ... ${end} 
<p>
```

**Comment by marcoscaceres** [comment] 2019-04-10 00:22
better yet... some kind of web component. 🤔

**Comment by andrea-perego** [comment] 2019-04-10 07:54
@marcoscaceres , just came to my mind a possible shortcoming of the HTML option - namely, if copyright and licence are specified via an HTML-encoded text, they cannot be used in the JSON+LD snippet generated via param [doJsonLd](https://github.com/w3c/respec/wiki/doJsonLd).

**Comment by marcoscaceres** [comment] 2019-04-10 07:57
Maybe we could extract the details from the HTML?

**Comment by andrea-perego** [comment] 2019-04-10 08:09
Isn't it a bit error-prone?

**Comment by marcoscaceres** [comment] 2019-04-10 08:12
I honestly don't know at this point... it depends how how we design the thing. I don't think it should be any more error prone than using JSON/config.

**Closed** 2019-12-26 01:59 UTC
Labels: Override
