### ISSUE TITLE
Add Linking to constructors in WebIDL 

### ISSUE THREAD

**Issue by mwatson2** [w3c/respec#900] opened 2016-08-02 17:53 UTC
```
[Constructor]
interface Foo
{
...
};
```

If I document the `Foo` constructor with `<dfn>Foo</dfn>`, then all links to `Foo` in the document point to the definition of the constructor (`#dom-foo`) and not to the IDL (`#idl-def-foo'). No amount of additional attributes on the`dfn` element seems to fix this.

**Comment by marcoscaceres** [comment] 2016-08-03 03:21
@mwatson2, sorry, can you provide just a tiny bit more text so I can make sure we fix this properly? Like, what would you like to describe about the Foo constructor. Some sample text/markup would be really helpful to see how to wire everything up.

**Comment by marcoscaceres** [comment] 2016-08-10 07:25
Ok, looked into this a bit more... Yeah, we sadly don't support this yet.

**Comment by marcoscaceres** [comment] 2016-08-10 07:25
changed to feature request.

**Comment by marcoscaceres** [comment] 2017-06-04 14:34
Duplicate of https://github.com/w3c/respec/issues/394

**Closed by marcoscaceres** 2017-06-04 14:34 UTC
Labels: bug, Feature request
