### ISSUE TITLE
Add "cite-summary" section magic

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1051] opened 2017-01-20 05:33 UTC
As a (wannabe) spec writer, I want to do the following:

```HTML
<p>...can manage <a data-cite="!payment-request#payment-method">payment methods</a>...</p>
<p>
   ...the <a>payment methods</a>... 
</p>
<section id="cite-summary"></section>
```

In other words, I should be able to `data-cite=` something once, and then have it magically defined in the  `cite-summary` section. And any anchors that match would be auto linked.

```HTML
<section id="cite-summary">
<p>The following are defined in [[!payment-request]]:</p>
<ul>
   <li><dfn data-cite="!payment-request#payment-method">payment methods</dfn></li>
</ul>
</section>
```

**Comment by anoited007** [comment] 2018-02-27 05:57
@marcoscaceres Can I take this on for GSOC 2018?

**Comment by marcoscaceres** [comment] 2018-02-27 05:59
Sure, this is basically part of the WebIDL rewrite.

**Comment by CodHeK** [comment] 2019-01-30 04:59
@marcoscaceres meanwhile can I work on this issue ?

**Comment by marcoscaceres** [comment] 2019-01-30 05:49
@CodHeK sure, that would be great! However, it's a fairly challenging one tho. You'll have to do a fair bit of investigating different parts of ReSpec to get it to work... basically, what should come out is a dynamically generated Dependencies section that looks something like this:

https://w3c.github.io/screen-orientation/#dependencies

Or this:
https://www.w3.org/TR/payment-request/#dependencies

**Comment by CodHeK** [comment] 2019-01-31 08:40
@marcoscaceres I did a bit fair of searching, I understood how data-cite works to generate the href link to the specified location ( mentioned in the `data-cite` attribute ) but I still am not sure about what you said about dependencies,  as in how is it related to generating dependencies ? Also, what all data needs to be in the `cite-summary` section ?

**Comment by marcoscaceres** [comment] 2019-02-01 05:03
> but I still am not sure about what you said about dependencies, as in how is it related to generating dependencies ? Also, what all data needs to be in the cite-summary section ?

So, let's imagine a simple case. As a spec editor, I only want to write: 

```HTML
<body>
<section>
  <h2>A section</h2>
  <p>You need to <a data-cite="dom#concept-event-fire">fire an event</a>.</p>
</section>

<section id="cite-summary"></section>
</body>
```

Now, I would expect ReSpec to generate something like this:

```HTML
<section id="cite-summary">
  <h2>Dependencies</h2>
  <p>The concept of <dfn data-cite="dom#concept-event-fire">fire an event</dfn> is defined in the  [[DOM]] specification.</p>
</section>
```

With the above all appropriately linked.

**Comment by CodHeK** [comment] 2019-02-03 09:47
@marcoscaceres  okay, so every cited link in the section needs to be added in the dependencies in the `cite-summary` section ?

**Comment by marcoscaceres** [comment] 2019-02-03 10:00
Yep, except if the document is citing itself. But any outside citation should appear there.

**Comment by CodHeK** [comment] 2019-02-03 19:59
@marcoscaceres if possible could you please help me with the flow, I am trying to understand how `data-cite` is working and how the cites are being distinguished and added to the document as normative or informative.

**Comment by CodHeK** [comment] 2019-02-04 05:11
This issue looks more like merging `normative` and `informative` sections containing tags which reference external docs into a dependencies sections, isin't it ?

Also, I believe I need to re-write `render-biblio.js` somehow to produce `cite-summary`, since that's where the HTML for the references section is being rendered right?

Theres this thing `conf.something` in many places ( for eg: `conf.normativeReferences` ), where does the `conf.` object reside ?

**Comment by sidvishnoi** [comment] 2019-11-25 10:33
Duplicate of https://github.com/w3c/respec/issues/2560

**Closed by sidvishnoi** 2019-11-25 10:33 UTC
Labels: enhancement
