### ISSUE TITLE
Some refs from HTML starting with "DOM" aren't available 

### ISSUE THREAD

**Issue by noamr** [w3c/respec#3441] opened 2021-04-08 09:24 UTC
## Important info

- URL to affected spec: https://w3c.github.io/navigation-timing/
- ReSpec version:26.5.0
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**
Some newly added HTML refs are available, but some aren't.
`[=document load timing info/load event start time=]` is available
`[=document load timing info/DOM content loaded event start time=]` is not available.
`[=document load timing info/DOM complete=]` is not available.

Seems like the struct fields starting with DOM are not available.

**Expected behavior (e.g., it shouldn't crash):**

The spec currently works around this by using `data-cite`, but really hard xrefs should be preferred.

**Comment by dontcallmedom** [comment] 2021-04-08 10:03
the problem is with how reffy handles the extraction of definitions from HTML spec - once https://github.com/w3c/reffy/pull/561 gets merged, the next update of [webref](https://github.com/w3c/webref/) should fix this.

**Comment by dontcallmedom** [comment] 2021-04-08 12:57
The definitions are there now, e.g. https://respec.org/xref/?term=dom+complete+time

**Closed** 2021-04-08 13:42 UTC
Labels: bug
