### ISSUE TITLE
Add Bikeshed like dfn-panels showing where terms are referenced

### ISSUE THREAD

**Issue by gsnedders** [w3c/respec#1869] opened 2018-11-05 14:23 UTC
## Important info

* URL to affected spec: https://w3c.github.io/payment-request/
* ReSpec version: 24.4.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: I clicked on a term (e.g., "payment method") and wanted to find places where the term is referenced. Nothing happened.

But what I was expecting?:

Compared with a spec that uses Bikeshed, like https://dom.spec.whatwg.org, when I click on a term it provides a panel showing uses of the term within the same spec. This is useful when looking at definitional issues to see where the term is used and test whether the behaviour of operations that use the term.

**Comment by marcoscaceres** [comment] 2018-11-06 10:41
Duplicate of https://github.com/w3c/respec/issues/1103 . Would indeed be a really nice addition. PR welcome! It might be nice to see if the JS for that feature can be generalized so we can use it across both ReSpec and BikeShed.

**Closed by marcoscaceres** 2018-11-06 10:41 UTC
