### ISSUE TITLE
xref error somewhat broken

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2358] opened 2019-05-23 05:26 UTC
Given: 

```HTML
<a data-cite="HTML">script</a>
```

It produces the following error: 

> The term "script" is defined in html in multiple ways, so it's ambiguous. To disambiguate, you need to add data-xref-for attribute with value equal to one of the following: undefined.

The undefined is wrong...

**Comment by sidvishnoi** [comment] 2019-07-26 12:35
Was working on error messages today. Turns out, the ambiguity can also be caused by "type", as in this case, but [we're just handling `forContext`](https://github.com/w3c/respec/blob/37628a272f982215aa795506172e2e7e3703c48e/src/core/xref.js#L411-L415)

How should we hint user to disambiguate based on type? Ask them to use `data-xref-type`? 

I was thinking to not give disambiguation/search hints in error messages (too many edge cases) and use xref UI to help users find proper cite syntax. We can add a "how to resolve this error" link/button in error message, linking to pre-filled xref UI and provide cite hints there only.

**Comment by marcoscaceres** [comment] 2019-07-30 06:01
> How should we hint user to disambiguate based on type? Ask them to use data-xref-type?

We generally want to avoid users ever writing `data-*`... if they can use the alternative syntax, that's better. 

> I was thinking to not give disambiguation/search hints in error messages (too many edge cases) and use xref UI to help users find proper cite syntax. We can add a "how to resolve this error" link/button in error message, linking to pre-filled xref UI and provide cite hints there only.

Yes, that would be good. We can even pop up xref right in the document as an iframe.

**Comment by sidvishnoi** [comment] 2019-07-30 07:15
> We can even pop up xref right in the document as an iframe.

That's the plan. Have some works in the local. Will try to send PRs today.

**Comment by sidvishnoi** [comment] 2019-08-01 08:15
Closed via https://github.com/w3c/respec/pull/2455

**Closed by sidvishnoi** 2019-08-01 08:15 UTC
Labels: xref
